// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLJBSSkrBsNAyAvZf13t2FAw1M1j3LIZ8',
    appId: '1:400455814117:web:a1f35f4aed8cdcaea93d0c',
    messagingSenderId: '400455814117',
    projectId: 'test1-eb8ab',
    authDomain: 'test1-eb8ab.firebaseapp.com',
    storageBucket: 'test1-eb8ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5gYRkqUGZTkump3IFj1dUSPgYrUYmXOk',
    appId: '1:400455814117:android:e8fdc2f31fd9951aa93d0c',
    messagingSenderId: '400455814117',
    projectId: 'test1-eb8ab',
    storageBucket: 'test1-eb8ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRn29WDxLtg3csTni1Gq9TnXhdFeELQEs',
    appId: '1:400455814117:ios:1aad678a608546a7a93d0c',
    messagingSenderId: '400455814117',
    projectId: 'test1-eb8ab',
    storageBucket: 'test1-eb8ab.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRn29WDxLtg3csTni1Gq9TnXhdFeELQEs',
    appId: '1:400455814117:ios:1aad678a608546a7a93d0c',
    messagingSenderId: '400455814117',
    projectId: 'test1-eb8ab',
    storageBucket: 'test1-eb8ab.firebasestorage.app',
    iosBundleId: 'com.example.test01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLJBSSkrBsNAyAvZf13t2FAw1M1j3LIZ8',
    appId: '1:400455814117:web:039bd72cd8fd4879a93d0c',
    messagingSenderId: '400455814117',
    projectId: 'test1-eb8ab',
    authDomain: 'test1-eb8ab.firebaseapp.com',
    storageBucket: 'test1-eb8ab.firebasestorage.app',
  );
}
